module.exports = {
    MONGO_DB_STRING:"String de conexion a mongo",
    MONGO_DB_SECONDARY:"Parte del secundario de la DB de mongo: Por ejemplo: LaikadVM21laikad.local:27017",
    MONGO_DB_OPTIONS:"?ssl=false&readPreference=secondary",
    WRITE_OUT_TIMER:"Tiempo en ms antes de escribir en la db para el cache, default 5000",
    MAX_SIZE_BEFORE_WRITE:"Tamaño maximo de objeto de cache en memoria (en bytes), por default 10000",
    REDIS_PORT:"Puerto de server redis",
    REDIS_HOST:"Host de server redis",
    COUNT_BEFORE_WRITE:'Por default 5000. Buffer antes de escribir ciertas updates en MongoDB',
    SILENT_MODE:"Si es 'true' no se envian logs a ninguna salida",
    MAX_CACHE_ELEMENTS:"Maximo de elementos a guardar en la cache",
    SERVER_THREAD_NUMS: "Numero de threads a correr. Idelmente debe ser igual a la cantidad de procesadores en el equipo. \ej: SERVER_THREAD_NUMS=2",
    SERVER_LISTENING_PORT: "Numero de puerto a en el cual levantar el proceso. \ej: SERVER_LISTENING_PORT=80",
    MAX_REQUESTS_PER_IP: "Cantidad maxima de request por IP \n ej: MAX_REQUESTS_PER_IP=10",
    RUN_SINGLE_INSTANCE: "Corre sin modo cluster si RUN_SINGLE_INSTANCE=true",
    MAX_UPLOAD_SIZE: "Tamaño maximo de Uploads permitidos \n ej: MAX_UPLOAD_SIZE=3mb",
    MSSQL_MAX_POOL_CONNECTIONS:"Conexiones maximas en el pool de MSSQL",
    MSSQL_MIN_POOL_CONNECTIONS:"Conexiones minimas siempre disponibles en el pool de MSSQL",
    MONGO_DB_HOST: "Host de mongo DB",
    MONGO_DB_PORT: "Puerto de la DB de Mongo, ej: 3448",
    MONGO_DB_PRIMARY: "SDegcQmy5wJBpLGcROwxQrLnffvDNeIKQvuwgqg2OIlUMbOGwYfqDtHLNeXYzQrr2CBtdJe4XOgTnKvsFuRAMA==",
    MONGO_DB_NAME: "laikad",
    MONGO_DB_USERNAME: "laikad-db",
    MONGO_DB_CLICK_EXPIRATION_IN_DAYS: "Dias que el registro creado en Clicks va a durar, valor sugerido[7]",
    CACHE_HELPER_STD_TTL: "TTL Para el cache si es que no se especifica uno en el guardado, valor sugerido[100]",
    CACHE_HELPER_CHECK_PERIOD: "Cada cuanto debería nodecache revisar el estado y limpiar?, valor sugerido[5]",
    FILE_DB_CARRIERS_PATH: "Path al archivo de Carriers de IP2",
    FILE_DB_PROXYS_PATH: "Path al archivo de Proxies de IP2",
    IS_DEVELOPER_ENV: "Variable de uso general para entorno desarrollo",
    PROJECT_ROOT_PATH_INCLUDING_LAST_SLASH: "Path completo a la raiz de la carpeta contenedora de la App",
    CACHE_TTK_ELEMENT_NO_ACTIVITY: "Minutos que deben pasar sin consultarse un objeto en la caché antes de olvidarse de el",
    CACHE_TTL: "Tiempo de refresco de caché para cada elemento, en segundos.",
    APM_ENABLED: "true|false Flag que indica si se habilita APM",
    APM_SERVER_URL: "URL de server apm ej: http://apm-server.solunika.com",
    APM_SERVER_TOKEN: "Si APM server requiere token",
    APM_SERVICE_NAME: "Nombre de instancia reportada en APM",
    MSSQL_SERVER: "IP o hostname del server de mssql",
    MSSQL_USER_NAME: "Usuario de coneccion a MSSQL",
    MSSQL_PASSWORD: "Password de la conexion de MSSQL",
    MSSQL_DATABASE_NAME: "Nombre de la base de datos de MSSQL",
    MSSQL_LOG: "Si se muestra el log de MSSQL o no, del pool",
    ELASTIC_SEARCH_URL: "La URL de un servidor con Elastic Seach para el envió de datos",
    REPORT_TO_ELASTIC_SEARCH: "",
    LOGMODE: "Opciones pueden ser console|elastic|silent",
    MONGO_DEBUG_LEVEL: "Puede ser: debug|error|info|warn",
    LOG_INDEX_NAME: "String: Nombre del indice de elastic search para guardar los logs.",
    ELASTIC_CLICKS_INDEX_NAME: "El nombre del indice de elastic para los clicks",
    ELASTIC_INSTALLS_INDEX_NAME: "El nombre del indice de elastic para los install",
    ELASTIC_EVENTS_INDEX_NAME: "El nombre del indice de elastic para los events",
    ELASTIC_DEBUG_INDEX_NAME: "El nombre del indice de elastic para debuggear una campa",
    API_KEY_SECRET: "Elija Una password para consultar las API administrativas",
    HEADER_TO_GET_IP_FROM: "ip|headers.x-forwarded-for|[otro]: Key de donde se saca la IP del cliente. Para cuando estás detrás de un nginx 'headers.x-forwarded-for' es la solución ideal junto con agregar en el upstream del nginx la configuracion  'proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;'",
    CLICK_COUNT_VALID: "Cantidad de Clicks a partir del cual realizo las validaciones, default = 20",
    MARGEN_DAILY: "Margen para Valido si hay porcentaje de Proxy en la Oferta para ver si hay que convertir, default = 1",
    CR_LIMITE: "Cantidad de Clicks desde los cuales inicio la validacion del CR Maximo, default = 7",
    MAX_IPs: "Maxima cantidad de instalaciones por ofertas desde una misma IP, default = 2",
    MONGO_DB_POOL_SIZE: "MONGO Max pool size, default = 100",
    IGNORED_VALIDATORS: "Valor separado por comas de los validadores a ignorar. p ex: Country,Device",
    APM_AGENT_TRANSACTION_SAMPLE_RATE:"Que porcentaje debe apm enviar como sample rate? si esta variable es 1, entonces se envia el 100%. Un buen valor es: 0.01",
    APM_AGENT_CAPTURE_SPAN_STACK_TRACES:"Set this option to false to disable capture of stack traces for measured spans during instrumentation."
}